### ISSUE TITLE
[Feature] Delay permission check

### ISSUE THREAD

**Issue by masmc05** [RodneyMKay/F3NPerm#2]
add a configurable delay for check, so plugins that works with permission (and removes them until an event) could finish their work first, and then with all permission to be able to play

also could be very useful a command to force check the permission and send the packet 

also i saw in code that you have a possibility to bypass the perm check, would be cool if you could move it to config

**Comment by RodneyMKay** [comment]
That's some really good points you bring up there. Thanks for the feedback! A big rewrite of the plugin has been on my ToDo-List for a while now and I just merged the corresponding branch into master after testing the "new plugin" on all versions from 1.9 - 1.18.2. I'll publish the 3.0 release very soon and update all of the documentation.

Notable features are:
- `/f3nperm reload` and `/f3nperm forceupdate [playername]` commands
- The option to use ProtocolLib, so that the plugin can still work on new versions when the plugin itself isn't updated yet
- A hook into LuckPerms to detect when the permission is changing (with the possibility of adding more permissions plugins in the future)
- Major change to the internal mechanism: Instead of listening to the all events that could possibly reset the player op status, I implemented a `ChannelDuplexHandler` that catches all of the outgoing packages that would take away the permission from the player and modify them to match their f3nperm permission level
- A couple more things I'm forgetting to mention

Again, your feedback sparked a lot of the ideas for those features, so thank you <3
