### ISSUE TITLE
Allowing only specific game modes

### ISSUE THREAD

**Issue by terbin** [RodneyMKay/F3NPerm#9]
I run a museum server that allows only Adventure and Spectator modes.

When a player tries to change from spectator using F3, I get a: permission denied switching to creative mode.

Is it possible to exclude creative and survival modes from F3NPerm so I only  switch between Adventure and Spectator?

**Comment by RodneyMKay** [comment]
Hi there 👋 
Thanks for your post! The only thing this plugin is doing is telling the vanilla client that it's okay to use the ``/gamemode`` commands. Therefore, any permission issues you might have should also occur when using the regular ``/gamemode`` commands. If the message doesn't have a yellow ``[DEBUG]`` in front, the issue is not related to this plugin and instead related to how the ``/gamemode`` command is set up in your environment.
I hope this helps.
If you believe that doesn't solve your issue, please don't hesitate to reopen this issue :D
